### PR TITLE
initial setup

### PR DESCRIPTION
**Pull request by Estorian**
As per 3.2

### CODE REVIEW

**Review by iamwill123 — CHANGES_REQUESTED** [review]
create a `.gitignore` file and add your `node_modules` to it, best practice is for it to be in your repo, only locally.

https://docs.github.com/en/free-pro-team@latest/github/using-git/ignoring-files

**Comment by Estorian** [comment]
I think I got this figured out. It would have been easier to gitignore those files had I known before hand to do so. As it was, it took backing them up, removing them from the folder, clearing the cache, adding the folder to the .gitignore file, pushing changes, and then re-adding them into the folder now that they were ignored.

**Comment by iamwill123** [comment]
It's all part of the "learning experience" now you know to never add node_modules to your GitHub repo 💯

**Comment by iamwill123** [comment]
You can merge this branch

**Pull request merged**
